apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: mlops
    gitKind: bitbucketserver
    gitName: bitbuket
    gitServer: https://bitbucket.weird-logic.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: noheroes
    repository: jx3-k8s
  - key: staging
  - key: production
  kaniko: true
  ingress:
    domain: ingress.local
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: noheroes
  repository: nexus
  secretStorage: local
  vault: {}
  webhook: lighthouse
